[package]
name = "fw"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "fw"
path = "src/main.rs"
test = false
doctest = false
bench = false

[dependencies]
stm32f3 = { version = "0.15", features = ["stm32f302", "rt"] }
cortex-m = { version = "0.7", features = ["inline-asm"] }
cortex-m-rt = "0.6"
